Squashed 'clproto/' changes from c84f2f9..684ad1b
684ad1b Merge pull request #77 in VFS/clproto from VFS-1035-Add-CMakeLists-to-protocol to feature/VFS-1034-oc-protocol-integration
be6f29f VFS-1035 Rewrite CMakeLists to allow building helpers as subproject.
f53a2c5 VFS-1034 Fix protocol compilation.
c421abf Merge pull request #76 in VFS/clproto from feature/VFS-1009-op-new-protocol-handler to develop
33a8317 beautify protocol v2
4c8508a beautify protocol
8584c8a VFS-997 Add stream message and descriptions + refactoring.
4b27927 change type od message_id from uint64 to bytes
9423229 change handshake message
e63b893 certificate msg extended
5f3db6c remove header
6f2b815 remove HandshakeAcknowledgement
2d2761d typo fix
2e5237e new handshake messages
2ea50b8 VFS-997 Extend protocol messages.
cbe54db Merge branch 'feature/VFS-1009-op-new-protocol-handler' of ssh://git.plgrid.pl:7999/vfs/clproto into feature/VFS-1005-new-protocol-oc-op
2b37656 rename 'oneof' messages
0069f68 add new proto file aggregating server and client messages
cfb51b4 remove HandshakeRequest data
2b72803 VFS-997 Add communication messages.
5ecbf14 Merge pull request #75 in VFS/clproto from feature/VFS-1005-new-protocol-oc-op to develop
fcd7b8b VFS-1005 Apply recommended changes.
b73c8bd VFS-1005 Minor fix for ServerMessage.
27bde46 VFS-1005 Change wrapping message structure.
613c3a8 VFs-1005 Add partial message mechanism.
50e3537 VFS-1005 Fix Erlang compilation errors.
6260815 VFS-1005 New protocol first implementation.
4bf6ec3 Merge pull request #68 in VFS/clproto from feature/VFS-960-access-to-fiemaps to develop
cbdfa01 GetFileBlockMap change uuid to logical name
a61592d GetFileBlockMap and FileBlockMap messages
d5e2d40 Merge pull request #67 in VFS/clproto from feature/VFS-936-async-update-for-file-attributes to develop

git-subtree-dir: clproto
git-subtree-split: 684ad1b1e95f7935341de3516a7db46a0e03f335